name: BigQuery - test query

on:
  push:
    branches:
      - main

jobs:
  run-bq:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'   # necess√°rio para autentica√ß√£o

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: primeiroprojeto-406719
          export_default_credentials: true

      - name: Run BigQuery SQL
        run: |
          echo "Running BigQuery test query..."
          bq query --nouse_legacy_sql \
            "SELECT CURRENT_TIMESTAMP() AS current_time, 'Tha√≠s Farias üå∏' AS user"
