name: BigQuery - run bq query

on:
  push:
    branches:
      - main

jobs:
  run-bq:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Install bq (Cloud SDK)
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: primeiroprojeto-406719
          export_default_credentials: true

      - name: Run BigQuery SQL
        run: |
          # exemplo simples: consulta de teste
          bq query --nouse_legacy_sql "SELECT CURRENT_TIMESTAMP() as current_time, 'ok' as status;"
